import 'dart:convert';

import 'model.dart';

const generatedVersionFile = 'dictionary_version.g.dart';
const generatedStrictFile = 'dictionary_strict_data.g.dart';
const generatedLenientFile = 'dictionary_lenient_data.g.dart';
const legacyGeneratedFile = 'dictionary_data.g.dart';

Map<String, String> renderDictionaryFiles(
  List<DictionaryEntry> entries,
  SourceManifest sources,
  String version,
) {
  final shared = _header()
    ..writeln("const String generatedDictionaryVersion = '$version';");
  final strict = _header();
  final lenient = _header();

  for (final tier in <String>['allow', 'strict']) {
    for (final mode in modes.toList()..sort()) {
      _writeWordMap(strict, entries, tier, mode);
    }
  }
  for (final mode in modes.toList()..sort()) {
    _writeWordMap(lenient, entries, 'lenient', mode);
  }
  _writeCountMap(lenient, 'generatedSourceCounts', {
    for (final id in sources.keys.toList()..sort())
      id: entries.where((entry) => entry.sourceId == id).length,
  });
  _writeCountMap(lenient, 'generatedTierCounts', {
    for (final tier in tiers.toList()..sort())
      tier: entries.where((entry) => entry.tier == tier).length,
  });
  _writeCountMap(lenient, 'generatedModeCounts', {
    for (final mode in modes.toList()..sort())
      mode: entries.where((entry) => entry.mode == mode).length,
  });
  return <String, String>{
    generatedVersionFile: _finish(shared),
    generatedStrictFile: _finish(strict),
    generatedLenientFile: _finish(lenient),
  };
}

StringBuffer _header() => StringBuffer()
  ..writeln('// GENERATED CODE - DO NOT MODIFY BY HAND.')
  ..writeln('// Generated by tool/generate_dictionary.dart.')
  ..writeln();

String _finish(StringBuffer output) => '${output.toString().trimRight()}\n';

void _writeWordMap(
  StringBuffer output,
  List<DictionaryEntry> entries,
  String tier,
  String mode,
) {
  final name = 'generated${_title(tier)}${_title(_camel(mode))}Words';
  final selected = entries
      .where((entry) => entry.tier == tier && entry.mode == mode)
      .toList();
  if (selected.isEmpty) {
    output.writeln('const Map<String, String> $name = <String, String>{};');
  } else {
    output.writeln('const Map<String, String> $name = <String, String>{');
    for (final entry in selected) {
      output.writeln(
        '  ${jsonEncode(entry.pattern)}: ${jsonEncode(entry.canonical)},',
      );
    }
    output.writeln('};');
  }
  output.writeln();
}

void _writeCountMap(
  StringBuffer output,
  String name,
  Map<String, int> counts,
) {
  output.writeln('const Map<String, int> $name = <String, int>{');
  for (final entry in counts.entries) {
    output.writeln('  ${jsonEncode(entry.key)}: ${entry.value},');
  }
  output.writeln('};');
  output.writeln();
}

String _camel(String value) {
  final parts = value.split('_');
  return parts.first + parts.skip(1).map(_title).join();
}

String _title(String value) => value[0].toUpperCase() + value.substring(1);
